// Editor.tsx
"use client";
import dynamic from "next/dynamic";
import { useMemo, useRef, useState, useEffect } from "react";
import "../Layouts/styles.css";

const JoditEditor = dynamic(() => import("jodit-react"), {
  ssr: false,
  loading: () => <div className="h-40 w-full animate-pulse bg-gray-200 rounded-md flex items-center justify-center">Loading Editor...</div>
});

type Props = {
  value: string;
  onChange: (val: string) => void;
  fullMode?: boolean;
  pasteOnlyMode?: boolean;
};

export default function Editor({ value, onChange, fullMode = false, pasteOnlyMode = false }: Props) {
  const editor = useRef(null);
  
  // Track the last value generated by the editor itself
  const lastHtmlRef = useRef(value);
  // This state is only updated when the parent passes a TRULY external value (e.g. clearing it)
  const [joditValue, setJoditValue] = useState(value);
  const [editorKey, setEditorKey] = useState(0);

  // Sync external changes (like clearing the input or loading a line to edit)
  useEffect(() => {
    if (value !== lastHtmlRef.current) {
      setJoditValue(value);
      lastHtmlRef.current = value;
      setEditorKey(k => k + 1); // Force remount on clear or external edit
    }
  }, [value]);

  const config = useMemo(
    () => ({
      readonly: false,
      placeholder: pasteOnlyMode ? "টাস্ক লিখুন বা পেস্ট করুন..." : "Start typing...",
      toolbar: !pasteOnlyMode,
      toolbarInline: !pasteOnlyMode,
      showTooltip: !pasteOnlyMode,
      disablePlugins: pasteOnlyMode ? "add-new-line,sticky,popup,inline-popup,xpath,stat" : "",
      showXPathInStatusbar: false,
      showCharsCounter: false,
      showWordsCounter: false,
      toolbarAdaptive: false,
      height: pasteOnlyMode ? "auto" : undefined,
      minHeight: pasteOnlyMode ? 44 : 200,
      buttons: fullMode 
        ? [
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "|",
            "ul",
            "ol",
            "|",
            "font",
            "fontsize",
            "brush",
            "paragraph",
            "|",
            "table",
            "link",
            "|",
            "align",
            "undo",
            "redo",
            "hr"
          ]
        : [
            "table",
            "addcolumn",
            "addrow",
            "merge",
            "split",
            "bin",
            "undo",
            "redo",
          ],
      removeButtons: fullMode 
        ? ["source", "image", "video", "file", "print", "fullsize", "spellcheck"] 
        : [
            "source",
            "bold",
            "italic",
            "underline",
            "ul",
            "ol",
            "font",
            "fontsize",
            "paragraph",
            "image",
            "video",
            "file",
            "link",
            "copyformat",
            "hr",
            "brush",
            "align",
            "outdent",
            "indent",
            "print",
            "fullsize",
            "spellcheck",
          ],
      style: {
        table: {
          width: '100%',
        },
      },
      defaultActionOnPaste: 'insert_as_html' as any,
      processPasteHTML: true,
      createAttributes: {
        table: {
          style: 'width:100%;border-collapse:collapse;',
        },
        td: {
          style: 'padding:6px 10px;border:1px solid #e0e7ff;',
        },
        th: {
          style: 'padding:8px 10px;border:1px solid #e0e7ff;background:#6366f1;color:#fff;text-align:center;',
        },
      },
    }),
    [fullMode, pasteOnlyMode],
  );

  return (
    <div
      className={pasteOnlyMode ? "[&_.jodit-container]:!border-none [&_.jodit-workplace]:!bg-transparent [&_.jodit-workplace]:!border-none [&_.jodit-status-bar]:!hidden" : ""}
      onMouseDown={(e) => e.stopPropagation()}
      onClick={(e) => e.stopPropagation()}
      onTouchStart={(e) => e.stopPropagation()}
    >
      <JoditEditor
        key={editorKey}
        ref={editor}
        value={joditValue}
        config={config}
        tabIndex={1}
        onBlur={(newContent) => {
          lastHtmlRef.current = newContent;
          onChange(newContent);
        }}
        onChange={(newContent) => {
          lastHtmlRef.current = newContent;
          onChange(newContent);
        }}
      />
    </div>
  );
}
